CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    status VARCHAR(255),
    admin_email VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    organization_id BIGINT,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id VARCHAR(255),
    status VARCHAR(255),
    total_price DECIMAL(19,2),
    currency VARCHAR(255),
    user_id BIGINT,
    organization_id BIGINT,
    contact_name VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(255),
    company_name VARCHAR(255),
    origin_address VARCHAR(255),
    destination_address VARCHAR(255),
    goods_description VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE tariffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode VARCHAR(255),
    origin_port VARCHAR(255),
    destination_port VARCHAR(255),
    price DECIMAL(19,2),
    currency VARCHAR(255),
    valid_from DATE,
    valid_to DATE,
    transit_time_days INTEGER,
    carrier_name VARCHAR(255)
);

CREATE TABLE commodities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    restricted BOOLEAN
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    type VARCHAR(255),
    country VARCHAR(255)
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    booking_id BIGINT,
    invoice_number VARCHAR(255),
    amount DECIMAL(19,2),
    currency VARCHAR(255),
    due_date DATE,
    status VARCHAR(255),
    pdf_url VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    booking_id BIGINT,
    type VARCHAR(255),
    amount DECIMAL(19,2),
    currency VARCHAR(255),
    status VARCHAR(255),
    reference VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    amount DECIMAL(19,2),
    reason VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    type VARCHAR(255),
    last4 VARCHAR(255),
    expiry_month VARCHAR(255),
    expiry_year VARCHAR(255),
    holder_name VARCHAR(255),
    token VARCHAR(255),
    is_default BOOLEAN
);

CREATE TABLE shipment_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT,
    title VARCHAR(255),
    description VARCHAR(255),
    status VARCHAR(255),
    due_date DATE
);

CREATE TABLE shipment_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT,
    type VARCHAR(255),
    name VARCHAR(255),
    url VARCHAR(255),
    uploaded_at TIMESTAMP
);

CREATE TABLE tracking_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT,
    status VARCHAR(255),
    location VARCHAR(255),
    description VARCHAR(255),
    timestamp TIMESTAMP
);

CREATE TABLE company_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    company_name VARCHAR(255),
    tax_id VARCHAR(255),
    address VARCHAR(255),
    kyc_status VARCHAR(255)
);

CREATE TABLE referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id VARCHAR(255),
    referee_email VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE content_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    body TEXT,
    type VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    title VARCHAR(255),
    message VARCHAR(255),
    type VARCHAR(255),
    is_read BOOLEAN,
    created_at TIMESTAMP
);
