'use client';

import React, { useEffect, useState } from 'react';
import { CreditCard, Trash2, Plus, Check } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8080';

interface PaymentMethod {
    id: number;
    type: string;
    last4: string;
    expiryMonth: string;
    expiryYear: string;
    holderName: string;
    isDefault: boolean;
}

export default function BillingPage() {
    const { token } = useAuth();
    const [methods, setMethods] = useState<PaymentMethod[]>([]);
    const [loading, setLoading] = useState(true);
    const [showAddForm, setShowAddForm] = useState(false);

    // New Card Form State
    const [newCard, setNewCard] = useState({
        holderName: '',
        cardNumber: '',
        expiryMonth: '',
        expiryYear: '',
        cvc: ''
    });

    useEffect(() => {
        if (token) {
            fetchMethods();
        } else {
            setLoading(false);
        }
    }, [token]);

    const fetchMethods = async () => {
        try {
            const res = await fetch(`${API_BASE}/api/payment-methods`, {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            if (res.ok) {
                setMethods(await res.json());
            }
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm('Are you sure you want to remove this payment method?')) return;
        try {
            await fetch(`${API_BASE}/api/payment-methods/${id}`, {
                method: 'DELETE',
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            fetchMethods();
        } catch (err) {
            console.error(err);
        }
    };

    const handleAddCard = async (e: React.FormEvent) => {
        e.preventDefault();
        // Mock tokenization
        const last4 = newCard.cardNumber.slice(-4);

        try {
            const res = await fetch(`${API_BASE}/api/payment-methods`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({
                    type: 'CARD',
                    last4: last4,
                    expiryMonth: newCard.expiryMonth,
                    expiryYear: newCard.expiryYear,
                    holderName: newCard.holderName,
                    // token is generated by backend mock
                })
            });

            if (res.ok) {
                setShowAddForm(false);
                setNewCard({ holderName: '', cardNumber: '', expiryMonth: '', expiryYear: '', cvc: '' });
                fetchMethods();
            } else {
                alert('Failed to save card. Please try again.');
            }
        } catch (err) {
            console.error(err);
            alert('An error occurred. Please check your connection.');
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 py-12 px-4 md:px-8">
            <div className="max-w-4xl mx-auto">
                <h1 className="text-3xl font-bold text-gray-800 mb-8">Billing & Payment Methods</h1>

                <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-8">
                    <div className="flex justify-between items-center mb-6">
                        <h2 className="text-xl font-bold text-gray-800">Saved Payment Methods</h2>
                        <button
                            onClick={() => setShowAddForm(true)}
                            className="flex items-center gap-2 text-blue-600 font-medium hover:bg-blue-50 px-3 py-2 rounded transition-colors"
                        >
                            <Plus className="w-4 h-4" /> Add New
                        </button>
                    </div>

                    {loading ? (
                        <div>Loading...</div>
                    ) : methods.length === 0 ? (
                        <div className="text-gray-500 text-center py-8">No payment methods saved.</div>
                    ) : (
                        <div className="space-y-4">
                            {methods.map(method => (
                                <div key={method.id} className="border border-gray-200 rounded-lg p-4 flex items-center justify-between hover:border-blue-300 transition-colors">
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-8 bg-gray-100 rounded flex items-center justify-center text-gray-600">
                                            <CreditCard className="w-6 h-6" />
                                        </div>
                                        <div>
                                            <div className="font-bold text-gray-800 flex items-center gap-2">
                                                •••• •••• •••• {method.last4}
                                                {method.isDefault && <span className="text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full">Default</span>}
                                            </div>
                                            <div className="text-sm text-gray-500">Expires {method.expiryMonth}/{method.expiryYear} • {method.holderName}</div>
                                        </div>
                                    </div>
                                    <button
                                        onClick={() => handleDelete(method.id)}
                                        className="text-gray-400 hover:text-red-500 p-2 transition-colors"
                                    >
                                        <Trash2 className="w-5 h-5" />
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Add Card Modal/Form Inline */}
                {showAddForm && (
                    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
                        <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
                            <h3 className="text-lg font-bold text-gray-800 mb-4">Add New Card</h3>
                            <form onSubmit={handleAddCard} className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Cardholder Name</label>
                                    <input required value={newCard.holderName} onChange={e => setNewCard({ ...newCard, holderName: e.target.value })} className="w-full border border-gray-300 rounded px-3 py-2 outline-none focus:border-blue-500" placeholder="John Doe" />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Card Number</label>
                                    <input required value={newCard.cardNumber} onChange={e => setNewCard({ ...newCard, cardNumber: e.target.value })} className="w-full border border-gray-300 rounded px-3 py-2 outline-none focus:border-blue-500" placeholder="0000 0000 0000 0000" maxLength={19} />
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">Expiry Date</label>
                                        <div className="flex gap-2">
                                            <input required value={newCard.expiryMonth} onChange={e => setNewCard({ ...newCard, expiryMonth: e.target.value })} className="w-full border border-gray-300 rounded px-3 py-2 outline-none focus:border-blue-500" placeholder="MM" maxLength={2} />
                                            <input required value={newCard.expiryYear} onChange={e => setNewCard({ ...newCard, expiryYear: e.target.value })} className="w-full border border-gray-300 rounded px-3 py-2 outline-none focus:border-blue-500" placeholder="YY" maxLength={2} />
                                        </div>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">CVC</label>
                                        <input required value={newCard.cvc} onChange={e => setNewCard({ ...newCard, cvc: e.target.value })} className="w-full border border-gray-300 rounded px-3 py-2 outline-none focus:border-blue-500" placeholder="123" maxLength={4} />
                                    </div>
                                </div>
                                <div className="flex justify-end gap-3 mt-6">
                                    <button type="button" onClick={() => setShowAddForm(false)} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded">Cancel</button>
                                    <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">Save Card</button>
                                </div>
                            </form>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
