server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=freightos
spring.datasource.password=freightos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=freightos-local

# 👉 IMPORTANTE: aquí ya NO hay spring.autoconfigure.exclude
# Config del Resource Server (Keycloak – más adelante lo terminamos de usar)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/freightos-local

